### ISSUE TITLE
Migrate this repository to the quickfeed organization

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed-swiftui#102]
We are moving away from the `autograde` organization. I'm not sure what, if anything needs to be updated in the repository to avoid any problems; e.g., import paths or other stuff referring to the `autograde` organization in various files in the repo.

**Comment by BjorniTe1** [comment]
There are no files in the SwiftUI application that need to be updated before a possible move from the autograde organization to the quickfeed organization. The only thing that will fail in this repo are two links in README.md. One that takes you to the QuickFeed server repo and the other that shows the image of the SwiftUI application.
